
package interfacePackage;
import logic.University;
import javax.swing.JOptionPane;


public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIngreso = new javax.swing.JButton();
        jBtnCambiarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jBtnIngreso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnIngreso.setText("Login");
        jBtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresoActionPerformed(evt);
            }
        });

        jBtnCambiarDatos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jBtnCambiarDatos.setText("Change data");
        jBtnCambiarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCambiarDatosActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2022_09_09_17_37_47_Greenshot.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(jBtnCambiarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jBtnIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jBtnCambiarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresoActionPerformed
     JOptionPane.showMessageDialog(null,"Welcome to " + University.getInstance().getName());
        
    }//GEN-LAST:event_jBtnIngresoActionPerformed

    private void jBtnCambiarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCambiarDatosActionPerformed
     University.getInstance().setName(" NYU ");
     JOptionPane.showMessageDialog(null," You sucessfully changed the university's name " + University.getInstance().getName());
    }//GEN-LAST:event_jBtnCambiarDatosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     this.setTitle(University.getInstance().getName());
    }//GEN-LAST:event_formWindowActivated
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCambiarDatos;
    private javax.swing.JButton jBtnIngreso;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
